extends: ht_2d/base.yaml

model: gns
num_mp_steps: 10
num_mlp_layers: 2
batch_size: 1
latent_dim: 128
lr_start: 1.e-4
step_max: 500000
log_steps: 1000
eval_steps: 10000
eval_n_trajs_infer: 1     #-1
eval_n_trajs: 50           #50
batch_size_infer: 1
loss_weight:
  acc: 1.0
  temp_diff: 1.0
wandb: True
noise_std: 0.0003 #0.0003
